### ISSUE TITLE
Compilation auto closes blocks without contents 

### ISSUE THREAD

**Issue by czipperz** [stevelacy/gulp-haml#13]
If I have an haml file of:

<code>
%html
    %body
        \#content
            blah
</code>

It will compile to
\<html>\</html>\<body>\</body>\<div id="content">\</div>blah

**Comment by czipperz** [comment]
Dang markdown. The haml example should be 4 lines

**Comment by stevelacy** [comment]
Not related to this project. Open on the compiler that you are using.

Either https://github.com/tj/haml.js or https://github.com/creationix/haml-js

**Comment by czipperz** [comment]
I understand but when I use either it compiles the same way, leading me to believe that it is your problem. Could you try compiling on your own computer?

**Comment by stevelacy** [comment]
This only renders, it does not alter or modify any data.
https://github.com/stevelacy/gulp-haml/blob/master/index.js#L23

That line:
```haml
 %html %body #content blah 
```
Compiles to:
```html
<html><body><div id="content">blah</div></body></html>
```
On my system.

Since both compilers are producing the same result for you, then there is an issue with your file, or encoding.

**Comment by czipperz** [comment]
Ok. Will do. What's your gulp file and plugins.json file? I could be going something wrong

**Comment by stevelacy** [comment]
https://github.com/stevelacy/gulp-haml/blob/master/examples/gulpfile.js

**Comment by czipperz** [comment]
What does use strict do https://github.com/stevelacy/gulp-haml/blob/master/examples/gulpfile.js#L1

**Comment by stevelacy** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode
