### ISSUE TITLE
How to add a no value attribute to a div with this plugin?

### ISSUE THREAD

**Issue by mikotan** [stevelacy/gulp-haml#15]
I try to use
  %div(ui-view)
but the result is
  < div >< /div >

gulpfile:
var haml = require('gulp-haml');
...
gulp.task('haml', function () {
  return gulp.src(PATHS.haml)
    .pipe(haml())
    .pipe(prettify())
    .pipe(gulp.dest('dist'));
});
...

**Comment by stevelacy** [comment]
Open any issues regarding haml on the respectable repos
