### ISSUE TITLE
This gulp plugin can "include" files?

### ISSUE THREAD

**Issue by HA3IK** [stevelacy/gulp-haml#16]
This gulp plugin can include files from paths?

For Example:

`-# "varFromGulp" is an interactive local variable with path from Gulp`
**`-# file: "some_path/#{varFromGulp}"`**

**Comment by stevelacy** [comment]
https://github.com/gulpjs/gulp/blob/master/docs/recipes/pass-arguments-from-cli.md

**Comment by HA3IK** [comment]
I meen in some "include" in .haml file:
