### ISSUE TITLE
Doesn't Support Tabs

### ISSUE THREAD

**Issue by stoodder** [stevelacy/gulp-haml#3]
When I compile my haml which is indented with the tab character. I get this:

`<!DOCTYPE html>
<html></html><head></head><title>Hello World</title><body></body>`

When I concert that same code to use spaces, I get what you would expect:

`<!DOCTYPE html>
<html><head><title>Hello World</title></head><body></body></html>`

**Comment by ptretyakov** [comment]
I has this problem too. Try -> "gulp-ruby-haml"
