### ISSUE TITLE
Option to output non-inline HTML

### ISSUE THREAD

**Issue by trevanhetzel** [stevelacy/gulp-haml#8]
I'm trying this out, just trying to convert a single Haml document into HTML5. It works great, but I feel like there's one thing missing: the ability to output uncompiled/unminified HTML. While that's great for performance and all, I just feel like spitting out HTML all in one line is not necessarily conventional and I could *really* get behind this plugin if you added that as an option :)

**Comment by stevelacy** [comment]
What do you mean by  'uncompiled/unminified'?

**Comment by czipperz** [comment]
It's all in one line of text without breaks where we use in haml documents

**Comment by fernandes** [comment]
this is because of the default haml compiler

> Note that this works almost the same as ruby's haml, but doesn't pretty print the html. This would greatly slow down and complicate the code. If you really want pretty printed html, then I suggest writing one using the xml parser library and process the resulting html..

[creationix/haml-js](https://github.com/creationix/haml-js#about-the-language)

**Comment by czipperz** [comment]
@fernandes I don't use HAML before. I made my own language ([HBML](http://github.com/czipperz/HBML))

**Comment by MattiJarvinen-BA** [comment]
https://www.npmjs.com/package/grunt-html-prettyprinter seems like a good fit for this?

**Comment by stevelacy** [comment]
@MattiJarvinen-BA  grunt? ...
